# Generated by Django 3.1 on 2020-09-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courency', models.CharField(choices=[('UAH', 'ukraine hryvna'), ('USD', 'Dollars'), ('RUB', 'russian rubles'), ('EUR', 'euros')], default='UAH', max_length=3)),
                ('balance', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_logic.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Extends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=256)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_logic.categories')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_logic.wallet')),
            ],
        ),
    ]
