# Generated by Django 3.1 on 2020-08-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.PositiveIntegerField(blank=True)),
                ('technology', models.PositiveIntegerField(blank=True)),
                ('play', models.PositiveIntegerField(blank=True)),
                ('study', models.PositiveIntegerField(blank=True)),
                ('health', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.IntegerField()),
                ('income', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending', to='core_logic.wallet')),
                ('name_cost', models.ManyToManyField(to='core_logic.Name_costs')),
            ],
        ),
    ]
