# Generated by Django 3.1.1 on 2020-09-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extend',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='core_logic.category'),
        ),
    ]
