# Generated by Django 3.1 on 2020-09-04 09:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('core_logic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Extends',
            new_name='Extend',
        ),
        migrations.RenameModel(
            old_name='Incomes',
            new_name='Income',
        ),
    ]
