# Generated by Django 3.1.1 on 2020-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_logic', '0005_auto_20200904_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='extend',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
